title: "おもちゃばこ"
description: "好きなことを好きなだけ詰め込む場所。宝物を増やしていこう。"
locale: ja
google_fonts: "M+PLUS+Rounded+1c"
minimal_mistakes_skin: default
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
