title: "おもちゃばこ"
description: "好きなことを好きなだけ詰め込む場所。宝物を増やしていこう。"
locale: ja
minimal_mistakes_skin: default
remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-include-cache
defaults:
  -
    scope:
      path: ""
    values:
      custom_css: "/assets/css/custom.css"
